"""Valida regras do 21, integração com robôs e áudio no desktop/celular."""
import io, wave
from playwright.sync_api import sync_playwright
from comum import AQUI, URL, ARGS, rota

with sync_playwright() as p:
    browser = p.chromium.launch(args=ARGS)
    for mobile in (False, True):
        page = browser.new_page(viewport={'width': 390 if mobile else 960, 'height': 760}, is_mobile=mobile, has_touch=mobile)
        page.route('**/*', rota)
        page.add_init_script('Object.defineProperty(navigator, "hardwareConcurrency", {get:()=>2})')
        page.add_init_script(path=AQUI + '/fake_supabase.js')
        page.add_init_script('HTMLCanvasElement.prototype.requestPointerLock=()=>Promise.resolve()')
        errors = []
        page.on('pageerror', lambda e: (errors.append(str(e)), print('ERRO:', e, flush=True)))
        print('Abrindo', 'celular' if mobile else 'desktop', flush=True)
        page.goto(URL + 'index.html#debug', wait_until='domcontentloaded')
        page.wait_for_function('!!window.__sala', timeout=120000)
        print('Sala carregada', flush=True)
        page.evaluate('__sala.renderer.setPixelRatio(0.4); __sala.renderer.setSize(innerWidth,innerHeight,false)')
        page.evaluate("__sala.setFP(-5.1,3.4,Math.PI); const r=__sala.robots.find(r=>!r.inPool); if(r.trade) __sala.closeTrade(r,'teste'); window.testRobot=r; __sala.openTalk(r)")
        page.get_by_role('button', name='Bora jogar 21?').click()
        assert page.evaluate("__sala.mode==='casino' && testRobot.inCasino && __sala.inGames(__sala.fp.pos.x,__sala.fp.pos.z)")
        print('Distribuindo cartas', flush=True)
        page.click('#casinoDeal')
        assert page.evaluate('__sala.CASINO.deck.length===48 && __sala.CASINO.balance>=90')
        assert page.evaluate("__sala.handValue([{rank:1},{rank:1},{rank:9}])===21 && __sala.handValue([{rank:1},{rank:13},{rank:8}])===19")
        # Cenários controlados para conferir liquidação, carta oculta e ás.
        def round_setup(you, bot, deck):
            page.evaluate('([you,bot,deck])=>{const c=__sala.CASINO; c.state="playing";c.balance=90;c.you=you.map(rank=>({rank,suit:"♠"}));c.bot=bot.map(rank=>({rank,suit:"♥"}));c.deck=deck.map(rank=>({rank,suit:"♦"}));}', [you, bot, deck])
        round_setup([10,7],[10,6],[10])
        page.evaluate('__sala.casinoStand()')
        assert page.evaluate('__sala.CASINO.balance===110 && __sala.CASINO.state==="over"')
        page.evaluate('__sala.casinoStand()')
        assert page.evaluate('__sala.CASINO.balance===110')
        round_setup([10,8],[10,8],[])
        page.evaluate('__sala.casinoStand()')
        assert page.evaluate('__sala.CASINO.balance===100')
        round_setup([10,6],[10,9],[10])
        page.evaluate('__sala.casinoHit()')
        assert page.evaluate('__sala.CASINO.balance===90 && __sala.CASINO.state==="over"')
        round_setup([10,7],[10,8],[])
        page.evaluate('__sala.casinoStand()')
        assert page.evaluate('__sala.CASINO.balance===90')
        print('Distribuindo cartas', flush=True)
        page.click('#casinoDeal')
        print('Regras OK; foto', flush=True)
        page.screenshot(timeout=120000, path=AQUI + '/saida/cassino-' + ('mobile' if mobile else 'desktop') + '.png')
        page.keyboard.press('Escape')
        assert page.evaluate('__sala.mode==="fp" && !testRobot.inCasino && !testRobot.talking')
        # A ação da mesa e saída pela vista aérea liberam o robô.
        page.evaluate('__sala.startCasino(testRobot); __sala.leaveRoom()')
        assert page.evaluate('!__sala.CASINO.active && !testRobot.inCasino')
        page.evaluate('__sala.setFP(-5.1,3.4,Math.PI); __sala.openMusic()')
        for style in ('lofi', 'lounge', 'electro'):
            page.select_option('#musicStyle', style)
            page.click('#musicPlay')
            page.wait_for_function('__sala.MUSIC.playing && __sala.MUSIC.ctx.state==="running"')
            page.click('#musicStop')
            assert page.evaluate('!__sala.MUSIC.playing && __sala.MUSIC.nodes.size===0 && __sala.MUSIC.timer===null')
        page.locator('#musicVolume').evaluate('(e)=>{e.value=70;e.dispatchEvent(new Event("input"))}')
        assert page.evaluate('__sala.MUSIC.audio.volume===0.7')
        audio = io.BytesIO()
        with wave.open(audio, 'wb') as wav:
            wav.setnchannels(1); wav.setsampwidth(2); wav.setframerate(8000); wav.writeframes(b'\0\0' * 8000)
        page.set_input_files('#musicFile', {'name':'teste.wav','mimeType':'audio/wav','buffer':audio.getvalue()})
        page.click('#musicPlay')
        page.wait_for_function('__sala.MUSIC.playing && !__sala.MUSIC.audio.paused')
        page.click('#musicClose')
        assert page.evaluate('__sala.mode==="fp" && __sala.MUSIC.playing')
        page.evaluate('__sala.openMusic()')
        page.click('#musicStop')
        page.screenshot(timeout=120000, path=AQUI + '/saida/musica-' + ('mobile' if mobile else 'desktop') + '.png')
        assert page.locator('#music').evaluate('(e)=>e.getBoundingClientRect().width <= innerWidth && e.getBoundingClientRect().top >= 0')
        page.keyboard.press('Escape')
        assert page.evaluate('__sala.mode==="fp"')
        assert not errors, errors
        print(('CELULAR' if mobile else 'DESKTOP') + ': TUDO OK', flush=True)
        page.close()
    browser.close()
